export const ACCOUNT_REQUEST_ME = 'ACCOUNT_REQUEST_ME';
export const ACCOUNT_REQUEST_ME_SUCCESS = 'ACCOUNT_REQUEST_ME_SUCCESS';
export const ACCOUNT_REQUEST_ME_FAIL = 'ACCOUNT_REQUEST_ME_FAIL';

export const ACCOUNT_REFRESH_TOKEN = 'ACCOUNT_REFRESH_TOKEN';
export const ACCOUNT_REFRESH_TOKEN_SUCCESS = 'ACCOUNT_REFRESH_TOKEN_SUCCESS';

export const ACCOUNT_LOGOUT = 'ACCOUNT_LOGOUT';
export const ACCOUNT_LOGOUT_SUCCESS = 'ACCOUNT_LOGOUT_SUCCESS';
export const ACCOUNT_LOGOUT_FAIL = 'ACCOUNT_LOGOUT_FAIL';

export const ACCOUNT_LOGIN = 'ACCOUNT_LOGIN';
export const ACCOUNT_LOGIN_SUCCESS = 'ACCOUNT_LOGIN_SUCCESS';
export const ACCOUNT_LOGIN_FAIL = 'ACCOUNT_LOGIN_FAIL';

export const ACCOUNT_REQUEST_USER_STATUS_SUCCESS = 'ACCOUNT_REQUEST_USER_STATUS_SUCCESS';
export const ACCOUNT_REQUEST_USER_STATUS_FAIL = 'ACCOUNT_REQUEST_USER_STATUS_FAIL';
export const ACCOUNT_UPDATE_USER_STATUS = 'ACCOUNT_UPDATE_USER_STATUS';
export const ACCOUNT_REQUEST_TRIAL_COURSE_SUCCESS = 'ACCOUNT_REQUEST_TRIAL_COURSE_SUCCESS';
export const ACCOUNT_REQUEST_TRIAL_COURSE_FAIL = 'ACCOUNT_REQUEST_TRIAL_COURSE_FAIL';
